/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DefaultRouteImport } from './routes/_default'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as DefaultIndexRouteImport } from './routes/_default/index'
import { Route as MalMalIdRouteImport } from './routes/mal.$malId'
import { Route as LListIdRouteImport } from './routes/l.$listId'
import { Route as AniAniIdRouteImport } from './routes/ani.$aniId'
import { Route as DefaultUserIndexRouteImport } from './routes/_default/user/index'
import { Route as DefaultTermsIndexRouteImport } from './routes/_default/terms/index'
import { Route as DefaultSettingsIndexRouteImport } from './routes/_default/settings/index'
import { Route as DefaultSearchIndexRouteImport } from './routes/_default/search/index'
import { Route as DefaultPrivacyIndexRouteImport } from './routes/_default/privacy/index'
import { Route as DefaultPopularIndexRouteImport } from './routes/_default/popular/index'
import { Route as DefaultMangaIndexRouteImport } from './routes/_default/manga/index'
import { Route as DefaultLatestIndexRouteImport } from './routes/_default/latest/index'
import { Route as DefaultBookmarksIndexRouteImport } from './routes/_default/bookmarks/index'
import { Route as DefaultAccountIndexRouteImport } from './routes/_default/account/index'
import { Route as DefaultAboutIndexRouteImport } from './routes/_default/about/index'
import { Route as ApiV1RevalidateRouteImport } from './routes/api.v1.revalidate'
import { Route as AuthAuthOauthRouteImport } from './routes/_auth/auth/oauth'
import { Route as AuthAuthConfirmRouteImport } from './routes/_auth/auth/confirm'
import { Route as AuthAuthCallbackRouteImport } from './routes/_auth/auth/callback'
import { Route as DefaultUserUserIdIndexRouteImport } from './routes/_default/user/$userId/index'
import { Route as DefaultSyncMalIndexRouteImport } from './routes/_default/sync/mal/index'
import { Route as DefaultSyncAniIndexRouteImport } from './routes/_default/sync/ani/index'
import { Route as DefaultMangaMangaIdIndexRouteImport } from './routes/_default/manga/$mangaId/index'
import { Route as DefaultListsListIdIndexRouteImport } from './routes/_default/lists/$listId/index'
import { Route as DefaultGenreGenreIdIndexRouteImport } from './routes/_default/genre/$genreId/index'
import { Route as DefaultDevToastIndexRouteImport } from './routes/_default/dev/toast/index'
import { Route as DefaultAuthorAuthorIdIndexRouteImport } from './routes/_default/author/$authorId/index'
import { Route as DefaultAuthUpdatePasswordIndexRouteImport } from './routes/_default/auth/update-password/index'
import { Route as DefaultAuthSignUpIndexRouteImport } from './routes/_default/auth/sign-up/index'
import { Route as DefaultAuthSignUpSuccessIndexRouteImport } from './routes/_default/auth/sign-up-success/index'
import { Route as DefaultAuthLoginIndexRouteImport } from './routes/_default/auth/login/index'
import { Route as DefaultAuthForgotPasswordIndexRouteImport } from './routes/_default/auth/forgot-password/index'
import { Route as DefaultAuthErrorIndexRouteImport } from './routes/_default/auth/error/index'
import { Route as DefaultAccountSetupIndexRouteImport } from './routes/_default/account/setup/index'
import { Route as DefaultMangaMangaIdScanlatorSubIdIndexRouteImport } from './routes/_default/manga/$mangaId/$scanlator/$subId/index'
import { Route as DefaultMangaMangaIdScanlatorSubIdCommentsIndexRouteImport } from './routes/_default/manga/$mangaId/$scanlator/$subId/comments/index'

const DefaultRoute = DefaultRouteImport.update({
  id: '/_default',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DefaultIndexRoute = DefaultIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DefaultRoute,
} as any)
const MalMalIdRoute = MalMalIdRouteImport.update({
  id: '/mal/$malId',
  path: '/mal/$malId',
  getParentRoute: () => rootRouteImport,
} as any)
const LListIdRoute = LListIdRouteImport.update({
  id: '/l/$listId',
  path: '/l/$listId',
  getParentRoute: () => rootRouteImport,
} as any)
const AniAniIdRoute = AniAniIdRouteImport.update({
  id: '/ani/$aniId',
  path: '/ani/$aniId',
  getParentRoute: () => rootRouteImport,
} as any)
const DefaultUserIndexRoute = DefaultUserIndexRouteImport.update({
  id: '/user/',
  path: '/user/',
  getParentRoute: () => DefaultRoute,
} as any)
const DefaultTermsIndexRoute = DefaultTermsIndexRouteImport.update({
  id: '/terms/',
  path: '/terms/',
  getParentRoute: () => DefaultRoute,
} as any)
const DefaultSettingsIndexRoute = DefaultSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => DefaultRoute,
} as any)
const DefaultSearchIndexRoute = DefaultSearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => DefaultRoute,
} as any)
const DefaultPrivacyIndexRoute = DefaultPrivacyIndexRouteImport.update({
  id: '/privacy/',
  path: '/privacy/',
  getParentRoute: () => DefaultRoute,
} as any)
const DefaultPopularIndexRoute = DefaultPopularIndexRouteImport.update({
  id: '/popular/',
  path: '/popular/',
  getParentRoute: () => DefaultRoute,
} as any)
const DefaultMangaIndexRoute = DefaultMangaIndexRouteImport.update({
  id: '/manga/',
  path: '/manga/',
  getParentRoute: () => DefaultRoute,
} as any)
const DefaultLatestIndexRoute = DefaultLatestIndexRouteImport.update({
  id: '/latest/',
  path: '/latest/',
  getParentRoute: () => DefaultRoute,
} as any)
const DefaultBookmarksIndexRoute = DefaultBookmarksIndexRouteImport.update({
  id: '/bookmarks/',
  path: '/bookmarks/',
  getParentRoute: () => DefaultRoute,
} as any)
const DefaultAccountIndexRoute = DefaultAccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => DefaultRoute,
} as any)
const DefaultAboutIndexRoute = DefaultAboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => DefaultRoute,
} as any)
const ApiV1RevalidateRoute = ApiV1RevalidateRouteImport.update({
  id: '/api/v1/revalidate',
  path: '/api/v1/revalidate',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAuthOauthRoute = AuthAuthOauthRouteImport.update({
  id: '/auth/oauth',
  path: '/auth/oauth',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAuthConfirmRoute = AuthAuthConfirmRouteImport.update({
  id: '/auth/confirm',
  path: '/auth/confirm',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAuthCallbackRoute = AuthAuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => AuthRoute,
} as any)
const DefaultUserUserIdIndexRoute = DefaultUserUserIdIndexRouteImport.update({
  id: '/user/$userId/',
  path: '/user/$userId/',
  getParentRoute: () => DefaultRoute,
} as any)
const DefaultSyncMalIndexRoute = DefaultSyncMalIndexRouteImport.update({
  id: '/sync/mal/',
  path: '/sync/mal/',
  getParentRoute: () => DefaultRoute,
} as any)
const DefaultSyncAniIndexRoute = DefaultSyncAniIndexRouteImport.update({
  id: '/sync/ani/',
  path: '/sync/ani/',
  getParentRoute: () => DefaultRoute,
} as any)
const DefaultMangaMangaIdIndexRoute =
  DefaultMangaMangaIdIndexRouteImport.update({
    id: '/manga/$mangaId/',
    path: '/manga/$mangaId/',
    getParentRoute: () => DefaultRoute,
  } as any)
const DefaultListsListIdIndexRoute = DefaultListsListIdIndexRouteImport.update({
  id: '/lists/$listId/',
  path: '/lists/$listId/',
  getParentRoute: () => DefaultRoute,
} as any)
const DefaultGenreGenreIdIndexRoute =
  DefaultGenreGenreIdIndexRouteImport.update({
    id: '/genre/$genreId/',
    path: '/genre/$genreId/',
    getParentRoute: () => DefaultRoute,
  } as any)
const DefaultDevToastIndexRoute = DefaultDevToastIndexRouteImport.update({
  id: '/dev/toast/',
  path: '/dev/toast/',
  getParentRoute: () => DefaultRoute,
} as any)
const DefaultAuthorAuthorIdIndexRoute =
  DefaultAuthorAuthorIdIndexRouteImport.update({
    id: '/author/$authorId/',
    path: '/author/$authorId/',
    getParentRoute: () => DefaultRoute,
  } as any)
const DefaultAuthUpdatePasswordIndexRoute =
  DefaultAuthUpdatePasswordIndexRouteImport.update({
    id: '/auth/update-password/',
    path: '/auth/update-password/',
    getParentRoute: () => DefaultRoute,
  } as any)
const DefaultAuthSignUpIndexRoute = DefaultAuthSignUpIndexRouteImport.update({
  id: '/auth/sign-up/',
  path: '/auth/sign-up/',
  getParentRoute: () => DefaultRoute,
} as any)
const DefaultAuthSignUpSuccessIndexRoute =
  DefaultAuthSignUpSuccessIndexRouteImport.update({
    id: '/auth/sign-up-success/',
    path: '/auth/sign-up-success/',
    getParentRoute: () => DefaultRoute,
  } as any)
const DefaultAuthLoginIndexRoute = DefaultAuthLoginIndexRouteImport.update({
  id: '/auth/login/',
  path: '/auth/login/',
  getParentRoute: () => DefaultRoute,
} as any)
const DefaultAuthForgotPasswordIndexRoute =
  DefaultAuthForgotPasswordIndexRouteImport.update({
    id: '/auth/forgot-password/',
    path: '/auth/forgot-password/',
    getParentRoute: () => DefaultRoute,
  } as any)
const DefaultAuthErrorIndexRoute = DefaultAuthErrorIndexRouteImport.update({
  id: '/auth/error/',
  path: '/auth/error/',
  getParentRoute: () => DefaultRoute,
} as any)
const DefaultAccountSetupIndexRoute =
  DefaultAccountSetupIndexRouteImport.update({
    id: '/account/setup/',
    path: '/account/setup/',
    getParentRoute: () => DefaultRoute,
  } as any)
const DefaultMangaMangaIdScanlatorSubIdIndexRoute =
  DefaultMangaMangaIdScanlatorSubIdIndexRouteImport.update({
    id: '/manga/$mangaId/$scanlator/$subId/',
    path: '/manga/$mangaId/$scanlator/$subId/',
    getParentRoute: () => DefaultRoute,
  } as any)
const DefaultMangaMangaIdScanlatorSubIdCommentsIndexRoute =
  DefaultMangaMangaIdScanlatorSubIdCommentsIndexRouteImport.update({
    id: '/manga/$mangaId/$scanlator/$subId/comments/',
    path: '/manga/$mangaId/$scanlator/$subId/comments/',
    getParentRoute: () => DefaultRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof DefaultIndexRoute
  '/ani/$aniId': typeof AniAniIdRoute
  '/l/$listId': typeof LListIdRoute
  '/mal/$malId': typeof MalMalIdRoute
  '/auth/callback': typeof AuthAuthCallbackRoute
  '/auth/confirm': typeof AuthAuthConfirmRoute
  '/auth/oauth': typeof AuthAuthOauthRoute
  '/api/v1/revalidate': typeof ApiV1RevalidateRoute
  '/about/': typeof DefaultAboutIndexRoute
  '/account/': typeof DefaultAccountIndexRoute
  '/bookmarks/': typeof DefaultBookmarksIndexRoute
  '/latest/': typeof DefaultLatestIndexRoute
  '/manga/': typeof DefaultMangaIndexRoute
  '/popular/': typeof DefaultPopularIndexRoute
  '/privacy/': typeof DefaultPrivacyIndexRoute
  '/search/': typeof DefaultSearchIndexRoute
  '/settings/': typeof DefaultSettingsIndexRoute
  '/terms/': typeof DefaultTermsIndexRoute
  '/user/': typeof DefaultUserIndexRoute
  '/account/setup/': typeof DefaultAccountSetupIndexRoute
  '/auth/error/': typeof DefaultAuthErrorIndexRoute
  '/auth/forgot-password/': typeof DefaultAuthForgotPasswordIndexRoute
  '/auth/login/': typeof DefaultAuthLoginIndexRoute
  '/auth/sign-up-success/': typeof DefaultAuthSignUpSuccessIndexRoute
  '/auth/sign-up/': typeof DefaultAuthSignUpIndexRoute
  '/auth/update-password/': typeof DefaultAuthUpdatePasswordIndexRoute
  '/author/$authorId/': typeof DefaultAuthorAuthorIdIndexRoute
  '/dev/toast/': typeof DefaultDevToastIndexRoute
  '/genre/$genreId/': typeof DefaultGenreGenreIdIndexRoute
  '/lists/$listId/': typeof DefaultListsListIdIndexRoute
  '/manga/$mangaId/': typeof DefaultMangaMangaIdIndexRoute
  '/sync/ani/': typeof DefaultSyncAniIndexRoute
  '/sync/mal/': typeof DefaultSyncMalIndexRoute
  '/user/$userId/': typeof DefaultUserUserIdIndexRoute
  '/manga/$mangaId/$scanlator/$subId/': typeof DefaultMangaMangaIdScanlatorSubIdIndexRoute
  '/manga/$mangaId/$scanlator/$subId/comments/': typeof DefaultMangaMangaIdScanlatorSubIdCommentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof DefaultIndexRoute
  '/ani/$aniId': typeof AniAniIdRoute
  '/l/$listId': typeof LListIdRoute
  '/mal/$malId': typeof MalMalIdRoute
  '/auth/callback': typeof AuthAuthCallbackRoute
  '/auth/confirm': typeof AuthAuthConfirmRoute
  '/auth/oauth': typeof AuthAuthOauthRoute
  '/api/v1/revalidate': typeof ApiV1RevalidateRoute
  '/about': typeof DefaultAboutIndexRoute
  '/account': typeof DefaultAccountIndexRoute
  '/bookmarks': typeof DefaultBookmarksIndexRoute
  '/latest': typeof DefaultLatestIndexRoute
  '/manga': typeof DefaultMangaIndexRoute
  '/popular': typeof DefaultPopularIndexRoute
  '/privacy': typeof DefaultPrivacyIndexRoute
  '/search': typeof DefaultSearchIndexRoute
  '/settings': typeof DefaultSettingsIndexRoute
  '/terms': typeof DefaultTermsIndexRoute
  '/user': typeof DefaultUserIndexRoute
  '/account/setup': typeof DefaultAccountSetupIndexRoute
  '/auth/error': typeof DefaultAuthErrorIndexRoute
  '/auth/forgot-password': typeof DefaultAuthForgotPasswordIndexRoute
  '/auth/login': typeof DefaultAuthLoginIndexRoute
  '/auth/sign-up-success': typeof DefaultAuthSignUpSuccessIndexRoute
  '/auth/sign-up': typeof DefaultAuthSignUpIndexRoute
  '/auth/update-password': typeof DefaultAuthUpdatePasswordIndexRoute
  '/author/$authorId': typeof DefaultAuthorAuthorIdIndexRoute
  '/dev/toast': typeof DefaultDevToastIndexRoute
  '/genre/$genreId': typeof DefaultGenreGenreIdIndexRoute
  '/lists/$listId': typeof DefaultListsListIdIndexRoute
  '/manga/$mangaId': typeof DefaultMangaMangaIdIndexRoute
  '/sync/ani': typeof DefaultSyncAniIndexRoute
  '/sync/mal': typeof DefaultSyncMalIndexRoute
  '/user/$userId': typeof DefaultUserUserIdIndexRoute
  '/manga/$mangaId/$scanlator/$subId': typeof DefaultMangaMangaIdScanlatorSubIdIndexRoute
  '/manga/$mangaId/$scanlator/$subId/comments': typeof DefaultMangaMangaIdScanlatorSubIdCommentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_default': typeof DefaultRouteWithChildren
  '/ani/$aniId': typeof AniAniIdRoute
  '/l/$listId': typeof LListIdRoute
  '/mal/$malId': typeof MalMalIdRoute
  '/_default/': typeof DefaultIndexRoute
  '/_auth/auth/callback': typeof AuthAuthCallbackRoute
  '/_auth/auth/confirm': typeof AuthAuthConfirmRoute
  '/_auth/auth/oauth': typeof AuthAuthOauthRoute
  '/api/v1/revalidate': typeof ApiV1RevalidateRoute
  '/_default/about/': typeof DefaultAboutIndexRoute
  '/_default/account/': typeof DefaultAccountIndexRoute
  '/_default/bookmarks/': typeof DefaultBookmarksIndexRoute
  '/_default/latest/': typeof DefaultLatestIndexRoute
  '/_default/manga/': typeof DefaultMangaIndexRoute
  '/_default/popular/': typeof DefaultPopularIndexRoute
  '/_default/privacy/': typeof DefaultPrivacyIndexRoute
  '/_default/search/': typeof DefaultSearchIndexRoute
  '/_default/settings/': typeof DefaultSettingsIndexRoute
  '/_default/terms/': typeof DefaultTermsIndexRoute
  '/_default/user/': typeof DefaultUserIndexRoute
  '/_default/account/setup/': typeof DefaultAccountSetupIndexRoute
  '/_default/auth/error/': typeof DefaultAuthErrorIndexRoute
  '/_default/auth/forgot-password/': typeof DefaultAuthForgotPasswordIndexRoute
  '/_default/auth/login/': typeof DefaultAuthLoginIndexRoute
  '/_default/auth/sign-up-success/': typeof DefaultAuthSignUpSuccessIndexRoute
  '/_default/auth/sign-up/': typeof DefaultAuthSignUpIndexRoute
  '/_default/auth/update-password/': typeof DefaultAuthUpdatePasswordIndexRoute
  '/_default/author/$authorId/': typeof DefaultAuthorAuthorIdIndexRoute
  '/_default/dev/toast/': typeof DefaultDevToastIndexRoute
  '/_default/genre/$genreId/': typeof DefaultGenreGenreIdIndexRoute
  '/_default/lists/$listId/': typeof DefaultListsListIdIndexRoute
  '/_default/manga/$mangaId/': typeof DefaultMangaMangaIdIndexRoute
  '/_default/sync/ani/': typeof DefaultSyncAniIndexRoute
  '/_default/sync/mal/': typeof DefaultSyncMalIndexRoute
  '/_default/user/$userId/': typeof DefaultUserUserIdIndexRoute
  '/_default/manga/$mangaId/$scanlator/$subId/': typeof DefaultMangaMangaIdScanlatorSubIdIndexRoute
  '/_default/manga/$mangaId/$scanlator/$subId/comments/': typeof DefaultMangaMangaIdScanlatorSubIdCommentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ani/$aniId'
    | '/l/$listId'
    | '/mal/$malId'
    | '/auth/callback'
    | '/auth/confirm'
    | '/auth/oauth'
    | '/api/v1/revalidate'
    | '/about/'
    | '/account/'
    | '/bookmarks/'
    | '/latest/'
    | '/manga/'
    | '/popular/'
    | '/privacy/'
    | '/search/'
    | '/settings/'
    | '/terms/'
    | '/user/'
    | '/account/setup/'
    | '/auth/error/'
    | '/auth/forgot-password/'
    | '/auth/login/'
    | '/auth/sign-up-success/'
    | '/auth/sign-up/'
    | '/auth/update-password/'
    | '/author/$authorId/'
    | '/dev/toast/'
    | '/genre/$genreId/'
    | '/lists/$listId/'
    | '/manga/$mangaId/'
    | '/sync/ani/'
    | '/sync/mal/'
    | '/user/$userId/'
    | '/manga/$mangaId/$scanlator/$subId/'
    | '/manga/$mangaId/$scanlator/$subId/comments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ani/$aniId'
    | '/l/$listId'
    | '/mal/$malId'
    | '/auth/callback'
    | '/auth/confirm'
    | '/auth/oauth'
    | '/api/v1/revalidate'
    | '/about'
    | '/account'
    | '/bookmarks'
    | '/latest'
    | '/manga'
    | '/popular'
    | '/privacy'
    | '/search'
    | '/settings'
    | '/terms'
    | '/user'
    | '/account/setup'
    | '/auth/error'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/sign-up-success'
    | '/auth/sign-up'
    | '/auth/update-password'
    | '/author/$authorId'
    | '/dev/toast'
    | '/genre/$genreId'
    | '/lists/$listId'
    | '/manga/$mangaId'
    | '/sync/ani'
    | '/sync/mal'
    | '/user/$userId'
    | '/manga/$mangaId/$scanlator/$subId'
    | '/manga/$mangaId/$scanlator/$subId/comments'
  id:
    | '__root__'
    | '/_auth'
    | '/_default'
    | '/ani/$aniId'
    | '/l/$listId'
    | '/mal/$malId'
    | '/_default/'
    | '/_auth/auth/callback'
    | '/_auth/auth/confirm'
    | '/_auth/auth/oauth'
    | '/api/v1/revalidate'
    | '/_default/about/'
    | '/_default/account/'
    | '/_default/bookmarks/'
    | '/_default/latest/'
    | '/_default/manga/'
    | '/_default/popular/'
    | '/_default/privacy/'
    | '/_default/search/'
    | '/_default/settings/'
    | '/_default/terms/'
    | '/_default/user/'
    | '/_default/account/setup/'
    | '/_default/auth/error/'
    | '/_default/auth/forgot-password/'
    | '/_default/auth/login/'
    | '/_default/auth/sign-up-success/'
    | '/_default/auth/sign-up/'
    | '/_default/auth/update-password/'
    | '/_default/author/$authorId/'
    | '/_default/dev/toast/'
    | '/_default/genre/$genreId/'
    | '/_default/lists/$listId/'
    | '/_default/manga/$mangaId/'
    | '/_default/sync/ani/'
    | '/_default/sync/mal/'
    | '/_default/user/$userId/'
    | '/_default/manga/$mangaId/$scanlator/$subId/'
    | '/_default/manga/$mangaId/$scanlator/$subId/comments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  DefaultRoute: typeof DefaultRouteWithChildren
  AniAniIdRoute: typeof AniAniIdRoute
  LListIdRoute: typeof LListIdRoute
  MalMalIdRoute: typeof MalMalIdRoute
  ApiV1RevalidateRoute: typeof ApiV1RevalidateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_default': {
      id: '/_default'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DefaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_default/': {
      id: '/_default/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DefaultIndexRouteImport
      parentRoute: typeof DefaultRoute
    }
    '/mal/$malId': {
      id: '/mal/$malId'
      path: '/mal/$malId'
      fullPath: '/mal/$malId'
      preLoaderRoute: typeof MalMalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/l/$listId': {
      id: '/l/$listId'
      path: '/l/$listId'
      fullPath: '/l/$listId'
      preLoaderRoute: typeof LListIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ani/$aniId': {
      id: '/ani/$aniId'
      path: '/ani/$aniId'
      fullPath: '/ani/$aniId'
      preLoaderRoute: typeof AniAniIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_default/user/': {
      id: '/_default/user/'
      path: '/user'
      fullPath: '/user/'
      preLoaderRoute: typeof DefaultUserIndexRouteImport
      parentRoute: typeof DefaultRoute
    }
    '/_default/terms/': {
      id: '/_default/terms/'
      path: '/terms'
      fullPath: '/terms/'
      preLoaderRoute: typeof DefaultTermsIndexRouteImport
      parentRoute: typeof DefaultRoute
    }
    '/_default/settings/': {
      id: '/_default/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof DefaultSettingsIndexRouteImport
      parentRoute: typeof DefaultRoute
    }
    '/_default/search/': {
      id: '/_default/search/'
      path: '/search'
      fullPath: '/search/'
      preLoaderRoute: typeof DefaultSearchIndexRouteImport
      parentRoute: typeof DefaultRoute
    }
    '/_default/privacy/': {
      id: '/_default/privacy/'
      path: '/privacy'
      fullPath: '/privacy/'
      preLoaderRoute: typeof DefaultPrivacyIndexRouteImport
      parentRoute: typeof DefaultRoute
    }
    '/_default/popular/': {
      id: '/_default/popular/'
      path: '/popular'
      fullPath: '/popular/'
      preLoaderRoute: typeof DefaultPopularIndexRouteImport
      parentRoute: typeof DefaultRoute
    }
    '/_default/manga/': {
      id: '/_default/manga/'
      path: '/manga'
      fullPath: '/manga/'
      preLoaderRoute: typeof DefaultMangaIndexRouteImport
      parentRoute: typeof DefaultRoute
    }
    '/_default/latest/': {
      id: '/_default/latest/'
      path: '/latest'
      fullPath: '/latest/'
      preLoaderRoute: typeof DefaultLatestIndexRouteImport
      parentRoute: typeof DefaultRoute
    }
    '/_default/bookmarks/': {
      id: '/_default/bookmarks/'
      path: '/bookmarks'
      fullPath: '/bookmarks/'
      preLoaderRoute: typeof DefaultBookmarksIndexRouteImport
      parentRoute: typeof DefaultRoute
    }
    '/_default/account/': {
      id: '/_default/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof DefaultAccountIndexRouteImport
      parentRoute: typeof DefaultRoute
    }
    '/_default/about/': {
      id: '/_default/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof DefaultAboutIndexRouteImport
      parentRoute: typeof DefaultRoute
    }
    '/api/v1/revalidate': {
      id: '/api/v1/revalidate'
      path: '/api/v1/revalidate'
      fullPath: '/api/v1/revalidate'
      preLoaderRoute: typeof ApiV1RevalidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/auth/oauth': {
      id: '/_auth/auth/oauth'
      path: '/auth/oauth'
      fullPath: '/auth/oauth'
      preLoaderRoute: typeof AuthAuthOauthRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/auth/confirm': {
      id: '/_auth/auth/confirm'
      path: '/auth/confirm'
      fullPath: '/auth/confirm'
      preLoaderRoute: typeof AuthAuthConfirmRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/auth/callback': {
      id: '/_auth/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthAuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_default/user/$userId/': {
      id: '/_default/user/$userId/'
      path: '/user/$userId'
      fullPath: '/user/$userId/'
      preLoaderRoute: typeof DefaultUserUserIdIndexRouteImport
      parentRoute: typeof DefaultRoute
    }
    '/_default/sync/mal/': {
      id: '/_default/sync/mal/'
      path: '/sync/mal'
      fullPath: '/sync/mal/'
      preLoaderRoute: typeof DefaultSyncMalIndexRouteImport
      parentRoute: typeof DefaultRoute
    }
    '/_default/sync/ani/': {
      id: '/_default/sync/ani/'
      path: '/sync/ani'
      fullPath: '/sync/ani/'
      preLoaderRoute: typeof DefaultSyncAniIndexRouteImport
      parentRoute: typeof DefaultRoute
    }
    '/_default/manga/$mangaId/': {
      id: '/_default/manga/$mangaId/'
      path: '/manga/$mangaId'
      fullPath: '/manga/$mangaId/'
      preLoaderRoute: typeof DefaultMangaMangaIdIndexRouteImport
      parentRoute: typeof DefaultRoute
    }
    '/_default/lists/$listId/': {
      id: '/_default/lists/$listId/'
      path: '/lists/$listId'
      fullPath: '/lists/$listId/'
      preLoaderRoute: typeof DefaultListsListIdIndexRouteImport
      parentRoute: typeof DefaultRoute
    }
    '/_default/genre/$genreId/': {
      id: '/_default/genre/$genreId/'
      path: '/genre/$genreId'
      fullPath: '/genre/$genreId/'
      preLoaderRoute: typeof DefaultGenreGenreIdIndexRouteImport
      parentRoute: typeof DefaultRoute
    }
    '/_default/dev/toast/': {
      id: '/_default/dev/toast/'
      path: '/dev/toast'
      fullPath: '/dev/toast/'
      preLoaderRoute: typeof DefaultDevToastIndexRouteImport
      parentRoute: typeof DefaultRoute
    }
    '/_default/author/$authorId/': {
      id: '/_default/author/$authorId/'
      path: '/author/$authorId'
      fullPath: '/author/$authorId/'
      preLoaderRoute: typeof DefaultAuthorAuthorIdIndexRouteImport
      parentRoute: typeof DefaultRoute
    }
    '/_default/auth/update-password/': {
      id: '/_default/auth/update-password/'
      path: '/auth/update-password'
      fullPath: '/auth/update-password/'
      preLoaderRoute: typeof DefaultAuthUpdatePasswordIndexRouteImport
      parentRoute: typeof DefaultRoute
    }
    '/_default/auth/sign-up/': {
      id: '/_default/auth/sign-up/'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up/'
      preLoaderRoute: typeof DefaultAuthSignUpIndexRouteImport
      parentRoute: typeof DefaultRoute
    }
    '/_default/auth/sign-up-success/': {
      id: '/_default/auth/sign-up-success/'
      path: '/auth/sign-up-success'
      fullPath: '/auth/sign-up-success/'
      preLoaderRoute: typeof DefaultAuthSignUpSuccessIndexRouteImport
      parentRoute: typeof DefaultRoute
    }
    '/_default/auth/login/': {
      id: '/_default/auth/login/'
      path: '/auth/login'
      fullPath: '/auth/login/'
      preLoaderRoute: typeof DefaultAuthLoginIndexRouteImport
      parentRoute: typeof DefaultRoute
    }
    '/_default/auth/forgot-password/': {
      id: '/_default/auth/forgot-password/'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password/'
      preLoaderRoute: typeof DefaultAuthForgotPasswordIndexRouteImport
      parentRoute: typeof DefaultRoute
    }
    '/_default/auth/error/': {
      id: '/_default/auth/error/'
      path: '/auth/error'
      fullPath: '/auth/error/'
      preLoaderRoute: typeof DefaultAuthErrorIndexRouteImport
      parentRoute: typeof DefaultRoute
    }
    '/_default/account/setup/': {
      id: '/_default/account/setup/'
      path: '/account/setup'
      fullPath: '/account/setup/'
      preLoaderRoute: typeof DefaultAccountSetupIndexRouteImport
      parentRoute: typeof DefaultRoute
    }
    '/_default/manga/$mangaId/$scanlator/$subId/': {
      id: '/_default/manga/$mangaId/$scanlator/$subId/'
      path: '/manga/$mangaId/$scanlator/$subId'
      fullPath: '/manga/$mangaId/$scanlator/$subId/'
      preLoaderRoute: typeof DefaultMangaMangaIdScanlatorSubIdIndexRouteImport
      parentRoute: typeof DefaultRoute
    }
    '/_default/manga/$mangaId/$scanlator/$subId/comments/': {
      id: '/_default/manga/$mangaId/$scanlator/$subId/comments/'
      path: '/manga/$mangaId/$scanlator/$subId/comments'
      fullPath: '/manga/$mangaId/$scanlator/$subId/comments/'
      preLoaderRoute: typeof DefaultMangaMangaIdScanlatorSubIdCommentsIndexRouteImport
      parentRoute: typeof DefaultRoute
    }
  }
}

interface AuthRouteChildren {
  AuthAuthCallbackRoute: typeof AuthAuthCallbackRoute
  AuthAuthConfirmRoute: typeof AuthAuthConfirmRoute
  AuthAuthOauthRoute: typeof AuthAuthOauthRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAuthCallbackRoute: AuthAuthCallbackRoute,
  AuthAuthConfirmRoute: AuthAuthConfirmRoute,
  AuthAuthOauthRoute: AuthAuthOauthRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DefaultRouteChildren {
  DefaultIndexRoute: typeof DefaultIndexRoute
  DefaultAboutIndexRoute: typeof DefaultAboutIndexRoute
  DefaultAccountIndexRoute: typeof DefaultAccountIndexRoute
  DefaultBookmarksIndexRoute: typeof DefaultBookmarksIndexRoute
  DefaultLatestIndexRoute: typeof DefaultLatestIndexRoute
  DefaultMangaIndexRoute: typeof DefaultMangaIndexRoute
  DefaultPopularIndexRoute: typeof DefaultPopularIndexRoute
  DefaultPrivacyIndexRoute: typeof DefaultPrivacyIndexRoute
  DefaultSearchIndexRoute: typeof DefaultSearchIndexRoute
  DefaultSettingsIndexRoute: typeof DefaultSettingsIndexRoute
  DefaultTermsIndexRoute: typeof DefaultTermsIndexRoute
  DefaultUserIndexRoute: typeof DefaultUserIndexRoute
  DefaultAccountSetupIndexRoute: typeof DefaultAccountSetupIndexRoute
  DefaultAuthErrorIndexRoute: typeof DefaultAuthErrorIndexRoute
  DefaultAuthForgotPasswordIndexRoute: typeof DefaultAuthForgotPasswordIndexRoute
  DefaultAuthLoginIndexRoute: typeof DefaultAuthLoginIndexRoute
  DefaultAuthSignUpSuccessIndexRoute: typeof DefaultAuthSignUpSuccessIndexRoute
  DefaultAuthSignUpIndexRoute: typeof DefaultAuthSignUpIndexRoute
  DefaultAuthUpdatePasswordIndexRoute: typeof DefaultAuthUpdatePasswordIndexRoute
  DefaultAuthorAuthorIdIndexRoute: typeof DefaultAuthorAuthorIdIndexRoute
  DefaultDevToastIndexRoute: typeof DefaultDevToastIndexRoute
  DefaultGenreGenreIdIndexRoute: typeof DefaultGenreGenreIdIndexRoute
  DefaultListsListIdIndexRoute: typeof DefaultListsListIdIndexRoute
  DefaultMangaMangaIdIndexRoute: typeof DefaultMangaMangaIdIndexRoute
  DefaultSyncAniIndexRoute: typeof DefaultSyncAniIndexRoute
  DefaultSyncMalIndexRoute: typeof DefaultSyncMalIndexRoute
  DefaultUserUserIdIndexRoute: typeof DefaultUserUserIdIndexRoute
  DefaultMangaMangaIdScanlatorSubIdIndexRoute: typeof DefaultMangaMangaIdScanlatorSubIdIndexRoute
  DefaultMangaMangaIdScanlatorSubIdCommentsIndexRoute: typeof DefaultMangaMangaIdScanlatorSubIdCommentsIndexRoute
}

const DefaultRouteChildren: DefaultRouteChildren = {
  DefaultIndexRoute: DefaultIndexRoute,
  DefaultAboutIndexRoute: DefaultAboutIndexRoute,
  DefaultAccountIndexRoute: DefaultAccountIndexRoute,
  DefaultBookmarksIndexRoute: DefaultBookmarksIndexRoute,
  DefaultLatestIndexRoute: DefaultLatestIndexRoute,
  DefaultMangaIndexRoute: DefaultMangaIndexRoute,
  DefaultPopularIndexRoute: DefaultPopularIndexRoute,
  DefaultPrivacyIndexRoute: DefaultPrivacyIndexRoute,
  DefaultSearchIndexRoute: DefaultSearchIndexRoute,
  DefaultSettingsIndexRoute: DefaultSettingsIndexRoute,
  DefaultTermsIndexRoute: DefaultTermsIndexRoute,
  DefaultUserIndexRoute: DefaultUserIndexRoute,
  DefaultAccountSetupIndexRoute: DefaultAccountSetupIndexRoute,
  DefaultAuthErrorIndexRoute: DefaultAuthErrorIndexRoute,
  DefaultAuthForgotPasswordIndexRoute: DefaultAuthForgotPasswordIndexRoute,
  DefaultAuthLoginIndexRoute: DefaultAuthLoginIndexRoute,
  DefaultAuthSignUpSuccessIndexRoute: DefaultAuthSignUpSuccessIndexRoute,
  DefaultAuthSignUpIndexRoute: DefaultAuthSignUpIndexRoute,
  DefaultAuthUpdatePasswordIndexRoute: DefaultAuthUpdatePasswordIndexRoute,
  DefaultAuthorAuthorIdIndexRoute: DefaultAuthorAuthorIdIndexRoute,
  DefaultDevToastIndexRoute: DefaultDevToastIndexRoute,
  DefaultGenreGenreIdIndexRoute: DefaultGenreGenreIdIndexRoute,
  DefaultListsListIdIndexRoute: DefaultListsListIdIndexRoute,
  DefaultMangaMangaIdIndexRoute: DefaultMangaMangaIdIndexRoute,
  DefaultSyncAniIndexRoute: DefaultSyncAniIndexRoute,
  DefaultSyncMalIndexRoute: DefaultSyncMalIndexRoute,
  DefaultUserUserIdIndexRoute: DefaultUserUserIdIndexRoute,
  DefaultMangaMangaIdScanlatorSubIdIndexRoute:
    DefaultMangaMangaIdScanlatorSubIdIndexRoute,
  DefaultMangaMangaIdScanlatorSubIdCommentsIndexRoute:
    DefaultMangaMangaIdScanlatorSubIdCommentsIndexRoute,
}

const DefaultRouteWithChildren =
  DefaultRoute._addFileChildren(DefaultRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  DefaultRoute: DefaultRouteWithChildren,
  AniAniIdRoute: AniAniIdRoute,
  LListIdRoute: LListIdRoute,
  MalMalIdRoute: MalMalIdRoute,
  ApiV1RevalidateRoute: ApiV1RevalidateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
